### ISSUE TITLE
Feature request: support mapint starting at index of 1

### ISSUE THREAD

**Issue by tux3** [vincenthz/cbored#2]
Hello,
The CTAP2 protocol (related to FIDO2/WebAuthn security keys) uses CBOR with map integer keys. However in their infinite wisdom, the map keys start from 1, instead of 0.

It would be useful if the mapint attribute could optionally take a starting value as an argument (keeping 0 as a good default)

**Comment by vincenthz** [comment]
I added a `maps_start_at` attribute, so this should work:

```rust
#[cborrepr(structure = "mapint", map_starts_at = 1)]
struct X {
...
}
```

let me know if that works for you
